extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.tdce]
pipeline = [
    "bril2json",
    "zsh tdce",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "zsh lvn-opt",
    "zsh tdce",
    "brili -p {args}",
]
